const Dados = (
    {
        Vara: req.body.nVara,
        Comarca: req.body.comarca, 
        NomeParte: req.body.nomeparte,
        Nacionalidade: req.body.nacionalidade,
        EstadoCivil: req.body.estadocivil,
        Profissao: req.body.profissao,
        Rg: req.body.rg, 
        OExp: req.body.orgaoexpedidor,
        Cpf: req.body.cpf,
        Email: req.body.email,
        Endereco: req.body.endereco,
        EndAdv: req.body.enderecoadvogado, 
        Acao: req.body.acao, 

        NomeReu: req.body.nomereu,
        NacReu: req.body.nacionalidadereu, 
        EstReu: req.body.estadocivilreu,
        ProReu: req.body.profissaoreu,
        RgReu: req.body.rgreu, 
        OExpReu: req.body.orgaoexpedidorreu, 
        CpfReu: req.body.cpfreu,
        EmailReu: req.body.emailreu,
        EndReu: req.body.enderecoreu,
        Relato: req.body.relato, 
        Fundamentos: req.body.fundamentos,
        Provas: req.body.provas, 
        Valor: req.body.valor,
        Local: req.body.local,
        Dia: req.body.dia, 
        Mes: req.body.mes,
        Ano: req.body.ano, 
        Advogado: req.body.advogado, 
        Oab: req.body.oab, 
        Uf: req.body.uf,
})